<?php
/**
 * @file
 */

/**
 * The machine name of the media folder vocabulary.
 */
define('IMAGEX_MEDIA_MEDIA_FOLDER_MACHINE_NAME', 'media_folders');

/**
 * Implements hook_permission().
 */
function imagex_media_permission() {
  return array(
    'edit terms in media_folders' => array(
      'name' => 'edit terms in media_folders',
    ),
    'delete terms in media_folders' => array(
      'name' => 'delete terms in media_folders',
    ),
  );
}

/**
 * Returns the media folder vocabulary object.
 *
 * @return mixed
 *   Returns an object representing the media folder vocabulary if it exists,
 *   otherwise returns FALSE.
 */
function imagex_media_get_media_folders_vocabulary() {
  return taxonomy_vocabulary_machine_name_load(IMAGEX_MEDIA_MEDIA_FOLDER_MACHINE_NAME);
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds form fields for wysiwyg settings but for use with ckeditor module
 * instead of wysiwyg module. The form labels are changed, but
 * the actual form fields and variables remain the same as found in
 * media_admin_config_browser().
 *
 * @see media module: media/includes/media.admin.inc
 */
function imagex_media_form_media_admin_config_browser_alter(&$form, &$form_state, $form_id) {

  $plugins = media_get_browser_plugin_info();

  // Additional configuration if the CKEDITOR module is enabled.
  $form['wysiwyg'] = array(
    '#type' => 'fieldset',
    '#title' => t('CKEDITOR configuration'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#access' => module_exists('ckeditor'),
  );
 
  $form['wysiwyg']['wysiwyg_browser_plugins'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enabled browser plugins'),
    '#options' => array(),
    '#required' => FALSE,
    '#default_value' => variable_get('wysiwyg_browser_plugins'),
    '#description' => t('If no plugins are selected, they will all be available.'),
  );
  foreach ($plugins as $key => $plugin) {
    $form['wysiwyg']['wysiwyg_browser_plugins']['#options'][$key] = !empty($plugin['title']) ? $plugin['title'] : $key;
  }
  $form['wysiwyg']['wysiwyg_upload_directory'] = array(
    '#type' => 'textfield',
    '#title' => t("File directory for uploaded media"),
    '#default_value' => variable_get('wysiwyg_upload_directory'),
    '#description' => t('Optional subdirectory within the upload destination where files will be stored. Do not include preceding or trailing slashes.'),
  );

  if (module_exists('token')) {
    $form['wysiwyg']['wysiwyg_upload_directory']['#description'] .= t('This field supports tokens.');
    $form['wysiwyg']['tokens'] = array(
      '#theme' => 'token_tree',
      '#dialog' => TRUE,
    ); 
  }

  $form['wysiwyg']['wysiwyg_allowed_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Allowed types in CKEDITOR'),
    '#options' => file_entity_type_get_names(),
    '#default_value' => variable_get('wysiwyg_allowed_types'),
  );

}